### PR TITLE
Specify explicit extensions for all imports

### PR DESCRIPTION
**Pull request by grant-cleary**
Required for an eventual move to Lit 2.0.

### CODE REVIEW

**Review by klhuff — APPROVED** [review]

**Comment by grant-cleary** [comment]
Boo, failure is legit. The ref used in the visual diff tests isn't right.

**Review by klhuff — APPROVED** [review]

**Comment by klhuff** [comment]
I don't know if it's intended or not, but this repo doesn't seem to remove approvals when additional changes are committed.

**Comment by grant-cleary** [comment]
> I don't know if it's intended or not, but this repo doesn't seem to remove approvals when additional changes are committed.

That is indeed intended.

**Comment by grant-cleary** [comment]
Hmm, so yeah, I'm kind of wondering if this new config just wasn't meant to apply to `require`d imports. Will dig in further.

**Pull request merged**
